#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80 make it return a page with
# "Hello" in it
sudo apt-update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello world!" > /var/www/html/index.html
