#!/usr/bin/env bash
# install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

#edit config file
server_config=\
"
frontend yaknos-frontend
	 bind *:80
	 mode http
	 default_backend yaknos-backend

backend yaknos-backend
	balance roundrobin
	server 671-web-01 34.138.141.3 check
	server 671-web-02 3.227.234.186 check
"
echo "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart