#!/usr/bin/env bash
# A script that displays, creates, deletes and sends a siginal

sig_term() {
    rm -f /var/run.myscript.pid
    echo "I hate the kill command"
    exit 0
}

sig_quit() {
    rm -f /var/run/myscript.pid
    exit 0
}

sig_int() {
    echo "Y U no love me>!"
    exit 0
}

trap sig_term TERM
trap sig_quit QUIT
trap sig_int INT

$$ > /var/run/myscript.pid

while true;
do
    echo "To infinity and beyond"
done
