#!/usr/bin/env bash
# Displaying "Best School" 10x, but for the 9th iteraration
# it displays "Best School" and then "hi" on a new line
count=0
while [[ $count -le 10 ]];
do
    echo "Best School";
    if [ $count -eq 9 ];
       then
       echo "Hi";
    fi;
    (( count++ ))
done;
