#!/usr/bin/env bash
0;276;0c# Display numbers 1 to 20 but also
Display superstitious numbers:
# numbers, omen and country of origin
a=1
while [ $a -le 20 ];
do
    echo $a
    case $a in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    (( a++ ));
done;
