#!/usr/bin/env bash
# Displays the time for 12hrs and 59mins
# It display hrs from 0 to 12
# It display mins from 1 to 59
h=0
m=1
while [[ $h -le 12 ]];
do
    echo "Hour: "$h
    while [[ $m -le 59 ]];
    do
	echo $m
	(( m++ ));
    done;
    (( m=1 ))
    (( h++ ));
done;
