#!/usr/bin/env bash
# A script that gives you info about the schoolfile
file="./school"
if [ -e $file ];
   then
   echo "school file exists"
   if [ -s $file ];
       then
       echo "school file is empty";
   else
       echo "school file is empty";
   fi;
   if [ -f $file ];
       then
       echo "school is a regular file";
   fi;
else
    echo "school file does not eixst";
fi
